meta_title: "Team8 - Défie des équipes proche de chez toi"
meta_description: "L'app number 1 pour tous les amateurs de basket!"
meta_image: "/basketball.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@LeWagonNantes" # indispensable pour les Twitter Cards
